# Site settings
baseurl = "https://rogiersbart.github.io/greetings/"
languageCode = "en-uk"
title = "greetings"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    # Meta
    title = "<img src='logo.png' width='100px'><br>[greetings](https://rogiersbart.github.io/greetings)"
    subtitle = "Our yearly season's greetings cards."
    author = "Bart Rogiers [rogiersbart]"
    description = ""
    keywords = ""

    # Body background color
    bodybgcolor = "#ffffff"

    # Preview container button text
    buttontext = "Download source"

    # Footer text
    footertext = '<center><p xmlns:dct="http://purl.org/dc/terms/" xmlns:cc="http://creativecommons.org/ns#" class="license-text">This work by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://rogiersbart.github.io/">Bart Rogiers</a> is licensed under <a rel="license" href="https://creativecommons.org/licenses/by/4.0">CC BY 4.0.</a></p></center><br>'

    # add extra-css
    # custom_css = ["css/extra1.css", "css/extra2.css"]
